=== ConePerez/LiSA/src/xml/LiSA.dtd
<!-- Syntax for xml problem notation -->

<!-- problem structure -->
<!ELEMENT problem (alpha, beta, gamma)>
<!-- problem namespace -->
<!ATTLIST problem xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- instance structure -->
<!ELEMENT instance (problem,values,controls?)>
<!-- instance namespace -->
<!ATTLIST instance xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- solution structure -->
<!ELEMENT solution (problem,values,controls?,schedule+)>
<!-- structure namespace -->
<!ATTLIST solution xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">

<!-- alpha element structure -->
<!-- Follows the structure of the common alpha|beta|gamma notation -->
<!ELEMENT alpha EMPTY>

<!-- alpha element attributes ... -->
<!-- env : machine environment -->
<!-- mpt : enable/disable multi purpose tasks -->
<!-- mpm : enable/disable multi purpose machines -->
<!-- m   : machine number tag (default is arbitrary) -->
<!--       set this to a number or "fixed" --> 
<!ATTLIST alpha
env              (1|O|F|J|X|
                 G|P|Q|R)      #REQUIRED 
mpt              (yes|no)      #IMPLIED
mpm              (yes|no)      #IMPLIED
m                CDATA         #IMPLIED>

<!-- beta element structure -->
<!ELEMENT beta EMPTY>
<!-- beta             : element attributes ... -->
<!-- pmtn             : enable/disable preemtion -->
<!-- prec             : enable/disable precedence constraints -->
<!--  release_times   : enable/disable release times -->
<!-- due_dates        : enable/disable due dates -->
<!-- processing_times : set special processing times flag -->
<!-- batch            : specify batch environment -->
<!-- batch_bounded    : enable/disable bounded batch -->
<!-- n                : job number tag (default is arbitrary) -->
<!--                    set this to a number or "fixed" -->
<!-- no-wait          : enable/disable "no-wait" schedule constraint -->
<!-- size             : enable/disable size constraint -->
<!-- time-lags        : enable/disable time lags -->
<!-- transp-delays    : specify transportaion delay requirements -->
<!-- server-flags     : specify server specific properties -->
<!ATTLIST beta
pmtn             (yes|no)      #IMPLIED
prec             (yes|no|intree|outtree|tree|sp_graph|chains)       #IMPLIED
release_times    (yes|no)      #IMPLIED
due_dates        (yes|no)      #IMPLIED
processing_times (arbitrary|unit|uniform) #IMPLIED
batch            (s_batch|p_batch)      #IMPLIED
batch_bounded    (yes|no)      #IMPLIED
n                CDATA         #IMPLIED
no-wait          (yes|no)      #IMPLIED
size             (yes|no)      #IMPLIED
time-lags        (no|unit|constant|given)        #IMPLIED
transp-delays    (no|t_ik--T| 
                 t_ikl--T|
                 t_i--T_1-T_2|
                 t_kl--t_lk| 
                 t_ikl--t_ilk|
                 t_i |t_k|t_kl|
                 t_ik|t_ikl)   #IMPLIED
server-flags     (no|yes|1|s)  #IMPLIED
>

<!-- gamma element structure -->
<!ELEMENT gamma EMPTY>
<!-- gamma element attributes ... -->
<!-- objective : set objective of problem -->
<!ATTLIST gamma
objective (Cmax|Lmax|Sum_Ci|Sum_wiCi|Sum_Ui|Sum_wiUi|Sum_Ti|Sum_wiTi|irreg_1|irreg_2) #REQUIRED
>

<!-- structure of values element -->
<!ELEMENT values (
processing_times,
operation_set,
machine_order?,
release_times?,
due_dates?,
weights?,
weights_2?,
extra? ) >

<!-- values element needs size of problem to be set ... -->
<!-- m  :  number of machines  -->
<!-- n  :  number of jobs  -->
<!ATTLIST values
m CDATA #REQUIRED
n CDATA #REQUIRED>

<!ELEMENT processing_times (#PCDATA)>
<!ATTLIST processing_times model CDATA "lisa_native">
<!ELEMENT operation_set (#PCDATA)>
<!ATTLIST operation_set model CDATA "lisa_native">
<!ELEMENT machine_order  (#PCDATA)>
<!ATTLIST machine_order model CDATA "lisa_native">
<!ELEMENT release_times (#PCDATA)>
<!ATTLIST release_times model CDATA "lisa_native">
<!ELEMENT due_dates (#PCDATA)>
<!ATTLIST due_dates model CDATA "lisa_native">
<!ELEMENT weights (#PCDATA)>
<!ATTLIST weights model CDATA "lisa_native">
<!ELEMENT weights_2 (#PCDATA)>
<!ATTLIST weights_2 model CDATA "lisa_native">
<!ELEMENT extra (#PCDATA)>
<!ATTLIST extra model CDATA "lisa_native">

<!-- Syntax for paramter notation -->
<!ELEMENT controls (parameter)* >
<!-- namespace -->
<!ATTLIST controls xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- no content -->
<!ELEMENT parameter EMPTY>

<!-- paramter element attributes ... -->
<!-- type  :  data type of the parameter -->
<!-- name  :  identifier of the parameter -->
<!-- value :  value of the paramter -->
<!ATTLIST parameter
type (integer|real|string) #REQUIRED
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!--schedule element structure -->
<!ELEMENT schedule (
plan?,
machine_sequences?,
job_sequences?,
completion_times?
)>

<!ELEMENT plan (#PCDATA)>
<!ATTLIST plan model CDATA "lisa_native">
<!ELEMENT machine_sequences (#PCDATA)>
<!ATTLIST machine_sequences model CDATA "lisa_native">
<!ELEMENT job_sequences (#PCDATA)>
<!ATTLIST job_sequences model CDATA "lisa_native">
<!ELEMENT completion_times (#PCDATA)>
<!ATTLIST completion_times model CDATA "lisa_native">

<!-- schedule needs size specification ... -->
<!-- m          :  number of machines -->
<!-- n          :  number of jobs -->
<!-- semiactive :  semiactive property flag -->
<!ATTLIST schedule 
m CDATA #REQUIRED
n CDATA #REQUIRED
semiactive (yes|no) #IMPLIED
>



<!-- Syntax for Algorithm description file -->

<!-- algorithm element structure -->
<!ELEMENT algorithm (((heuristic, exact )| heuristic | exact), alg_controls?)>
<!-- attributes of an algorithm ...-->
<!-- name       :  name of the algorithm (as displayed in selection menu etc.) -->
<!-- type       :  calculation approach, e.g. "constructive" or "iterative" -->
<!-- code       :  what kind of implementation, in most cases "external" -->
<!-- call       :  name of the executable file name (without extension) -->
<!-- help_file  :  file name of the HTML file to be browsed when user requests help -->
<!ATTLIST algorithm 
name CDATA #REQUIRED
type CDATA #REQUIRED
code CDATA #REQUIRED
call CDATA #REQUIRED
help_file CDATA #IMPLIED>

<!-- list problems the algorithm can approximate -->
<!ELEMENT heuristic (problem)*>
<!-- list problems the algorithm can solve exactly -->
<!ELEMENT exact (problem)*>

<!-- user interface definition -->
<!ELEMENT alg_controls (integer*, real*, choice*, fixed*)>

<!-- integer value parameter ...-->
<!ELEMENT integer EMPTY>
<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!-- default  :  guess what! (default value) -->
<!ATTLIST integer
name CDATA #REQUIRED
caption CDATA #REQUIRED
default CDATA #REQUIRED
>

<!-- real value parameter -->
<!ELEMENT real EMPTY>
<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!-- default  :  guess what! (default value) -->
<!ATTLIST real
name CDATA #REQUIRED
caption CDATA #REQUIRED
default CDATA #REQUIRED
>

<!-- choice of a list of strings -->
<!ELEMENT choice (item+)>

<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!ATTLIST choice
name CDATA #REQUIRED
caption CDATA #REQUIRED
>

<!-- item to be chosen from in a choice box -->
<!ELEMENT item EMPTY>
<!-- name of the item, i.e. the value of the parameter if selected -->
<!ATTLIST item name CDATA #REQUIRED>

<!-- a fixed control element (not displayed) -->
<!ELEMENT fixed EMPTY>
<!-- name  : identifier of parameter -->
<!-- value : fixed value of parameter -->
<!ATTLIST fixed 
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== ConePerez/LiSA/src/algorithm/nb_iter/nb_iter_SAnewO_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Simulated Annealing" type="iterative" call="nb_iter" code="external" help_file="algorithm/nb_iter_SA_english.html">
  <heuristic>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
  </heuristic>
  <alg_controls>
    <real name="TSTART" caption="Start temperature" default="20"/>
    <real name="TEND" caption="End temperature" default="0.9"/>
    <choice name="COOLSCHEME" caption="Cooling scheme">
      <item name="LINEAR"/>
      <item name="GEOMETRIC"/>
      <item name="LUNDYANDMEES"/>
    </choice>
    <real name="COOLPARAM" caption="Cooling parameter" default="0.0005"/>
    <integer name="EPOCH" caption="Epoch length" default="100"/>
    <integer name="NUMB_NGHB" caption="Number of neighbors" 
default="1"/>
    <integer name="STEPS" caption="Iteration steps" default="50000"/>
    <integer name="NUMB_STUCKS" caption="Abort when stuck for (stopping criterion)" 
default="100000"/>
    <real name="ABORT_BOUND" caption="Abort when reaching objective (stopping criterion)" default="0"/>
    <integer name="k" caption="k for k_API or k_REINSERTION" default="3"/>
    <choice name="NGBH" caption="Neighborhood">
      <item name="CR_TST"/>
      <item name="k_API"/>
      <item name="SHIFT"/>
      <item name="PI"/>
      <item name="CR_API"/>
      <item name="BL_API"/>
      <item name="CR_SHIFT"/>
      <item name="BL_SHIFT"/>
      <item name="3_CR"/>
      <item name="k_REINSERTION"/>
    </choice>
    <fixed name="METHOD" value="SimulatedAnnealingNew"/>
    <fixed name="TYPE" value="RAND"/>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/beam_aco/beam_aco_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Beam Ant Colony" type="constructive" call="beam_aco" code="external" help_file="algorithm/beam_aco.html">
  <heuristic>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
  </heuristic>
  <alg_controls>
    <integer name="BEAM_WIDTH" caption="Beam width" default="100"/>
    <real name="LOWER_BOUND" caption="Lower bound" default="0"/>
    <real name="UPPER_BOUND" caption="Upper bound" default="1e+06"/>
    <choice name="EXTENSION_STRATEGY" caption="Determination of beam extensions">
      <item name="MED"/>
      <item name="LDS"/>
      <item name="FIXED"/>
    </choice>
    <integer name="FIXED_KEXT" caption="Number of beam extensions" default="10"/>
    <choice name="APPEND_STRATEGY" caption="Strategy of selection of extensions">
      <item name="ORIGINAL"/>
      <item name="SORTED"/>
      </choice>
    <choice name="PRE_SELECTION" caption="Pre-selection of extensions">
      <item name="NONE"/>
      <item name="ACTIVE"/>
     </choice>
    <integer name="STEPS" caption="Number of runs" default="50"/>
    <real name="CONVERGENCE_FACTOR" caption="Convergence factor for re-start" default="0.98"/>
    <real name="EVAPORATION_RATE" caption="Evaporation rate" default="0.3"/>
    <real name="WEIGHT_EST" caption="Influence of Earliest Completion Time" default="1"/>
  <real name="WEIGHT_TIJ" caption="Influence of pheromone values" default="1"/>
  <real name="WEIGHT_RAND" caption="Influence of randomness" default="1"/>

  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/os_sum_ti/os_sum_ti_german.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="os_sum_ti Algorithmus" type="constructive" call="os_sum_ti" code="external" help_file="algorithm/os_sum_ti_german.html">
  <heuristic>
    <problem>
      <alpha env="O"/>
      <beta />
      <gamma objective="Sum_Ti"/>
    </problem>
  </heuristic>
  <exact>
    <problem>
      <alpha env="O"/>
      <beta processing_times="unit"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta processing_times="unit" no-wait="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
  </exact>
  <alg_controls>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/beam_aco/beamACO_german.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Beam Ant Colony" type="constructive" call="beamACO" code="external" help_file="algorithm/beamACO.html">
  <heuristic>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
  </heuristic>
  <alg_controls>
    <integer name="BEAM_WIDTH" caption="Beamweite" default="100"/>
    <real name="LOWER_BOUND" caption="Untere Schranke" default="0"/>
    <real name="UPPER_BOUND" caption="Obere Schranke" default="1e+06"/>
    <choice name="EXTENSION_STRATEGY" caption="Bestimmung der Beam Extensions">
      <item name="MED"/>
      <item name="LDS"/>
    </choice>
    <integer name="STEPS" caption="Anzahl Durchlaeufe" default="50"/>
    <real name="CONVERGENCE_FACTOR" caption="Konvergenzfaktor fuer Neustart" default="0.9"/>
    <real name="EVAPORATION_RATE" caption="evaporationRate" default="0.7" />
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/beam_aco/beamACO_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Beam Ant Colony" type="constructive" call="beamACO" code="external" help_file="algorithm/beamACO.html">
  <heuristic>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
  </heuristic>
  <alg_controls>
    <integer name="BEAM_WIDTH" caption="beam width" default="100"/>
    <real name="LOWER_BOUND" caption="lower bound" default="0"/>
    <real name="UPPER_BOUND" caption="upper bound" default="1e+06"/>
    <choice name="EXTENSION_STRATEGY" caption="extension strategy">
      <item name="MED"/>
      <item name="LDS"/>
    </choice>
    <integer name="STEPS" caption="steps" default="50"/>
    <real name="CONVERGENCE_FACTOR" caption="convergence factor for restart" default="0.9"/>
    <real name="EVAPORATION_RATE" caption="evaporation rate" default="0.7" />
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/nb_iter/nb_iter_TS1_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Tabu Search" type="iterative" call="nb_iter" code="external" help_file="algorithm/nb_iter.html">
  <heuristic>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
  </heuristic>
  <alg_controls>
    <integer name="STEPS" caption="Created Solutions" default="5000"/>
    <integer name="TABULENGTH" caption="Tabu List Length" default="40"/>
    <integer name="NUMB_NGHB" caption="Number of Neighbours" default="40"/>
    <real name="ABORT_BOUND" caption="Abort when reaching Objective (Abort Criterion)" default="0"/>
    <choice name="NGBH" caption="Neighbourhood">
      <item name="1_API"/>
      <item name="SHIFT"/>
      <item name="PI"/>
    </choice>
    <fixed name="METHOD" value="TabuSearch"/>
    <choice name="TYPE" caption="Create Neighbour">
      <item name="ENUM"/>
      <item name="RAND"/>
    </choice>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/partition/partition_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Partition alg. (Research)" type="constructive" call="partition" code="external" help_file="algorithm/partition.html">
  <exact>
    <problem>
      <alpha env="O" m="2"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="P" m="2"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
  </exact>
  <alg_controls/>
</algorithm>

=== ConePerez/LiSA/src/algorithm/js_bb_br/js_bb_br_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Brucker's Job-Shop B&amp;B" type="constructive" call="js_bb_br" code="external" help_file="algorithm/js_bb_br.html">
  <exact>
    <problem>
      <alpha env="J"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
  </exact>
  <alg_controls/>
</algorithm>
