=== ConePerez/LiSA/src/xml/LiSA.dtd
<!-- Syntax for xml problem notation -->

<!-- problem structure -->
<!ELEMENT problem (alpha, beta, gamma)>
<!-- problem namespace -->
<!ATTLIST problem xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- instance structure -->
<!ELEMENT instance (problem,values,controls?)>
<!-- instance namespace -->
<!ATTLIST instance xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- solution structure -->
<!ELEMENT solution (problem,values,controls?,schedule+)>
<!-- structure namespace -->
<!ATTLIST solution xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">

<!-- alpha element structure -->
<!-- Follows the structure of the common alpha|beta|gamma notation -->
<!ELEMENT alpha EMPTY>

<!-- alpha element attributes ... -->
<!-- env : machine environment -->
<!-- mpt : enable/disable multi purpose tasks -->
<!-- mpm : enable/disable multi purpose machines -->
<!-- m   : machine number tag (default is arbitrary) -->
<!--       set this to a number or "fixed" --> 
<!ATTLIST alpha
env              (1|O|F|J|X|
                 G|P|Q|R)      #REQUIRED 
mpt              (yes|no)      #IMPLIED
mpm              (yes|no)      #IMPLIED
m                CDATA         #IMPLIED>

<!-- beta element structure -->
<!ELEMENT beta EMPTY>
<!-- beta             : element attributes ... -->
<!-- pmtn             : enable/disable preemtion -->
<!-- prec             : enable/disable precedence constraints -->
<!--  release_times   : enable/disable release times -->
<!-- due_dates        : enable/disable due dates -->
<!-- processing_times : set special processing times flag -->
<!-- batch            : specify batch environment -->
<!-- batch_bounded    : enable/disable bounded batch -->
<!-- n                : job number tag (default is arbitrary) -->
<!--                    set this to a number or "fixed" -->
<!-- no-wait          : enable/disable "no-wait" schedule constraint -->
<!-- size             : enable/disable size constraint -->
<!-- time-lags        : enable/disable time lags -->
<!-- transp-delays    : specify transportaion delay requirements -->
<!-- server-flags     : specify server specific properties -->
<!ATTLIST beta
pmtn             (yes|no)      #IMPLIED
prec             (yes|no|intree|outtree|tree|sp_graph|chains)       #IMPLIED
release_times    (yes|no)      #IMPLIED
due_dates        (yes|no)      #IMPLIED
processing_times (arbitrary|unit|uniform) #IMPLIED
batch            (s_batch|p_batch)      #IMPLIED
batch_bounded    (yes|no)      #IMPLIED
n                CDATA         #IMPLIED
no-wait          (yes|no)      #IMPLIED
size             (yes|no)      #IMPLIED
time-lags        (no|unit|constant|given)        #IMPLIED
transp-delays    (no|t_ik--T| 
                 t_ikl--T|
                 t_i--T_1-T_2|
                 t_kl--t_lk| 
                 t_ikl--t_ilk|
                 t_i |t_k|t_kl|
                 t_ik|t_ikl)   #IMPLIED
server-flags     (no|yes|1|s)  #IMPLIED
>

<!-- gamma element structure -->
<!ELEMENT gamma EMPTY>
<!-- gamma element attributes ... -->
<!-- objective : set objective of problem -->
<!ATTLIST gamma
objective (Cmax|Lmax|Sum_Ci|Sum_wiCi|Sum_Ui|Sum_wiUi|Sum_Ti|Sum_wiTi|irreg_1|irreg_2) #REQUIRED
>

<!-- structure of values element -->
<!ELEMENT values (
processing_times,
operation_set,
machine_order?,
release_times?,
due_dates?,
weights?,
weights_2?,
extra? ) >

<!-- values element needs size of problem to be set ... -->
<!-- m  :  number of machines  -->
<!-- n  :  number of jobs  -->
<!ATTLIST values
m CDATA #REQUIRED
n CDATA #REQUIRED>

<!ELEMENT processing_times (#PCDATA)>
<!ATTLIST processing_times model CDATA "lisa_native">
<!ELEMENT operation_set (#PCDATA)>
<!ATTLIST operation_set model CDATA "lisa_native">
<!ELEMENT machine_order  (#PCDATA)>
<!ATTLIST machine_order model CDATA "lisa_native">
<!ELEMENT release_times (#PCDATA)>
<!ATTLIST release_times model CDATA "lisa_native">
<!ELEMENT due_dates (#PCDATA)>
<!ATTLIST due_dates model CDATA "lisa_native">
<!ELEMENT weights (#PCDATA)>
<!ATTLIST weights model CDATA "lisa_native">
<!ELEMENT weights_2 (#PCDATA)>
<!ATTLIST weights_2 model CDATA "lisa_native">
<!ELEMENT extra (#PCDATA)>
<!ATTLIST extra model CDATA "lisa_native">

<!-- Syntax for paramter notation -->
<!ELEMENT controls (parameter)* >
<!-- namespace -->
<!ATTLIST controls xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- no content -->
<!ELEMENT parameter EMPTY>

<!-- paramter element attributes ... -->
<!-- type  :  data type of the parameter -->
<!-- name  :  identifier of the parameter -->
<!-- value :  value of the paramter -->
<!ATTLIST parameter
type (integer|real|string) #REQUIRED
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!--schedule element structure -->
<!ELEMENT schedule (
plan?,
machine_sequences?,
job_sequences?,
completion_times?
)>

<!ELEMENT plan (#PCDATA)>
<!ATTLIST plan model CDATA "lisa_native">
<!ELEMENT machine_sequences (#PCDATA)>
<!ATTLIST machine_sequences model CDATA "lisa_native">
<!ELEMENT job_sequences (#PCDATA)>
<!ATTLIST job_sequences model CDATA "lisa_native">
<!ELEMENT completion_times (#PCDATA)>
<!ATTLIST completion_times model CDATA "lisa_native">

<!-- schedule needs size specification ... -->
<!-- m          :  number of machines -->
<!-- n          :  number of jobs -->
<!-- semiactive :  semiactive property flag -->
<!ATTLIST schedule 
m CDATA #REQUIRED
n CDATA #REQUIRED
semiactive (yes|no) #IMPLIED
>



<!-- Syntax for Algorithm description file -->

<!-- algorithm element structure -->
<!ELEMENT algorithm (((heuristic, exact )| heuristic | exact), alg_controls?)>
<!-- attributes of an algorithm ...-->
<!-- name       :  name of the algorithm (as displayed in selection menu etc.) -->
<!-- type       :  calculation approach, e.g. "constructive" or "iterative" -->
<!-- code       :  what kind of implementation, in most cases "external" -->
<!-- call       :  name of the executable file name (without extension) -->
<!-- help_file  :  file name of the HTML file to be browsed when user requests help -->
<!ATTLIST algorithm 
name CDATA #REQUIRED
type CDATA #REQUIRED
code CDATA #REQUIRED
call CDATA #REQUIRED
help_file CDATA #IMPLIED>

<!-- list problems the algorithm can approximate -->
<!ELEMENT heuristic (problem)*>
<!-- list problems the algorithm can solve exactly -->
<!ELEMENT exact (problem)*>

<!-- user interface definition -->
<!ELEMENT alg_controls (integer*, real*, choice*, fixed*)>

<!-- integer value parameter ...-->
<!ELEMENT integer EMPTY>
<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!-- default  :  guess what! (default value) -->
<!ATTLIST integer
name CDATA #REQUIRED
caption CDATA #REQUIRED
default CDATA #REQUIRED
>

<!-- real value parameter -->
<!ELEMENT real EMPTY>
<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!-- default  :  guess what! (default value) -->
<!ATTLIST real
name CDATA #REQUIRED
caption CDATA #REQUIRED
default CDATA #REQUIRED
>

<!-- choice of a list of strings -->
<!ELEMENT choice (item+)>

<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!ATTLIST choice
name CDATA #REQUIRED
caption CDATA #REQUIRED
>

<!-- item to be chosen from in a choice box -->
<!ELEMENT item EMPTY>
<!-- name of the item, i.e. the value of the parameter if selected -->
<!ATTLIST item name CDATA #REQUIRED>

<!-- a fixed control element (not displayed) -->
<!ELEMENT fixed EMPTY>
<!-- name  : identifier of parameter -->
<!-- value : fixed value of parameter -->
<!ATTLIST fixed 
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== ConePerez/LiSA/src/algorithm/dispatch/dispatch1_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Smith Rule" type="constructive" call="dispatch" code="external" help_file="algorithm/dispatch.html">
  <heuristic>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
  </heuristic>
  <exact>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
  </exact>
  <alg_controls>
    <fixed name="SCHEDULE" value="SEMIACTIVE"/>
    <choice name="RULE" caption="priority">
      <item name="WSPT"/>
    </choice>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/dispatch/dispatch1_german.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Smith-Regel" type="constructive" call="dispatch" code="external" help_file="algorithm/dispatch.html">
  <heuristic>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
  </heuristic>
  <exact>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
  </exact>
  <alg_controls>
    <fixed name="ACTIVE" value="FALSE"/>
    <choice name="RULE" caption="Prioritaetsregel">
      <item name="WSPT"/>
    </choice>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/dispatch/dispatch3_german.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Aktiver Plan" type="constructive" call="dispatch" code="external" help_file="algorithm/dispatch.html">
  <exact>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes" processing_times="unit"/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta processing_times="unit"/>
      <gamma objective="Cmax"/>
    </problem>
  </exact>
  <alg_controls>
    <choice name="ACTIVE" caption="Aktiven Plan erzeugen">
      <item name="TRUE"/>
    </choice>
    <choice name="RULE" caption="Prioritaetsregel">
      <item name="RAND"/>
      <item name="FCFS"/>
    </choice>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/beam/beam_german_att.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Beam Search (Anfügen)" type="constructive" call="beam" code="external" help_file="algorithm/beam_att_german.html">
  <heuristic>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
      <problem>
       <alpha env="1"/>
       <beta/>
       <gamma objective="Sum_Ci"/>
      </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
     <problem>
       <alpha env="1"/>
       <beta release_times="yes"/>
       <gamma objective="Sum_Ci"/>
     </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
     <problem>
       <alpha env="O"/>
       <beta/>
       <gamma objective="Sum_Ci"/>
     </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
     <problem>
       <alpha env="O"/>
       <beta release_times="yes"/>
       <gamma objective="Sum_Ci"/>
     </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Lmax"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Sum_Ci"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Sum_wiCi"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Sum_Ui"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Sum_wiUi"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Sum_Ti"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Sum_wiTi"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Lmax"/> -->
<!--     </problem> -->
<!--       <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Sum_Ci"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Sum_wiCi"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Sum_Ui"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Sum_wiUi"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Sum_Ti"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Sum_wiTi"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta/> -->
<!--       <gamma objective="Cmax"/> -->
<!--     </problem> -->
<!--     <problem> -->
<!--       <alpha env="F"/> -->
<!--       <beta release_times="yes"/> -->
<!--       <gamma objective="Cmax"/> -->
<!--     </problem> -->
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
  </heuristic>
  <exact>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
  </exact>
  <alg_controls>
    <integer name="K_BRANCHES" caption="Anzahl zu verfolgender Zweige" default="5"/>
    <choice name="INS_METHOD" caption="Auswahlmethode">
      <item name="INSERT1"/>
      <item name="INSERT2"/>
    </choice>
    <choice name="CRITERION" caption="Auswahlkriterium">
      <item name="CLAST"/>
      <item name="LB(Sum_Ci)"/>
      <item name="OBJECTIVE"/>
    </choice>
    <choice name="ATTACH_WHAT" caption="Anfügekriterium">
      <item name="Machines"/>
      <item name="Jobs"/>
      <item name="Machines+Jobs"/>
    </choice>
    <choice name="BREAK_TIES" caption="Tie Breaking">
	<item name="LPT"/>
	<item name="SPT"/>
	<item name="RANDOM"/>
	<item name="FCFS"/>
    </choice>
    <fixed name="MODE" value="ATTACH"/>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/sample/problem/o10x10cmax.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE solution PUBLIC "" "../data/LiSA.dtd">
<solution xmlns:LiSA="http://lisa.math.uni-magdeburg.de">
  <problem>
    <alpha env="O"/>
    <beta/>
    <gamma objective="Cmax"/>
  </problem>
  <values m="10" n="10">
    <processing_times model="lisa_native">{
 { 48 59 41 27 46 4 32 3 79 90 }
 { 17 97 42 33 84 30 83 52 87 51 }
 { 95 44 34 92 6 86 83 60 90 36 }
 { 90 13 43 76 33 91 98 17 68 85 }
 { 44 98 76 24 20 81 29 76 1 89 }
 { 10 16 93 88 78 73 99 97 18 92 }
 { 49 67 34 19 6 47 54 63 65 30 }
 { 90 11 48 20 34 73 74 87 28 14 }
 { 57 6 78 94 25 56 15 2 33 91 }
 { 77 19 17 44 28 88 55 42 92 32 }
}
</processing_times>
    <operation_set model="lisa_native">{
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
 { 1 1 1 1 1 1 1 1 1 1 }
}
</operation_set>
  </values>
  <schedule m="10" n="10" semiactive="yes">
    <plan model="lisa_native">{
 { 4 6 3 13 2 7 1 12 14 15 }
 { 6 5 11 10 8 12 2 14 7 1 }
 { 1 10 4 6 17 8 11 15 3 13 }
 { 13 14 9 3 4 5 10 2 1 12 }
 { 11 1 10 15 14 13 16 6 12 2 }
 { 8 9 12 1 11 14 5 4 2 10 }
 { 7 12 8 9 10 2 3 11 15 4 }
 { 12 13 2 14 1 3 6 5 9 11 }
 { 9 4 1 5 16 10 15 3 8 6 }
 { 2 11 15 16 6 1 14 13 10 5 }
}
</plan>
    <completion_times model="lisa_native">{
 { 220 290 167 518 80 303 32 491 597 689 }
 { 248 231 494 452 419 525 134 615 335 51 }
 { 95 480 230 350 681 436 563 675 196 599 }
 { 674 687 374 164 197 299 474 85 68 559 }
 { 494 98 450 650 626 606 679 371 503 187 }
 { 312 328 612 88 519 685 302 203 106 441 }
 { 297 588 331 369 425 135 189 488 662 219 }
 { 584 599 126 619 34 208 376 295 410 455 }
 { 439 104 78 258 658 495 633 87 382 349 }
 { 172 521 635 694 279 88 618 563 502 251 }
}
</completion_times>
  </schedule>
</solution>

=== ConePerez/LiSA/src/algorithm/beam/beam_german3.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Beam Search" type="constructive" call="beam" code="external" help_file="algorithm/beam.html">
  <heuristic>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ci"/>
    </problem>
  </heuristic>
  <exact>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
  </exact>
  <alg_controls>
    <integer name="K_BRANCHES" caption="Anzahl zu verfolgender Zweige" default="5"/>
    <choice name="INS_ORDER" caption="Einfuegereihenfolge">
      <item name="MACHINEWISE"/>
      <item name="DIAGONAL"/>
      <item name="QUEEN_SWEEP"/>
      <item name="RANDOM"/>
      <item name="LPT"/>
      <item name="ECT"/>
      <item name="SPT"/>
      <item name="ATTATCH"/>
    </choice>
    <choice name="INS_METHOD" caption="Auswahlmethode">
      <item name="INSERT1"/>
      <item name="INSERT2"/>
    </choice>
    <choice name="ATTATCH_WHAT" caption="Anfügekriterium">
      <item name="Machines"/>
      <item name="Jobs"/>
      <item name="Machines+Jobs"/>
    </choice>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/nb_iter/nb_iter3_english.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Neighbourhood Search" type="iterative" call="nb_iter" code="external" help_file="algorithm/nb_iter.html">
  <heuristic>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
  </heuristic>
  <alg_controls>
    <integer name="STEPS" caption="Created Solutions" default="5000"/>
    <integer name="NUMB_STUCKS" caption="Stuck Since (Abort Criterion)" default="10000"/>
    <integer name="PROB" caption="Start Parameter (Only for SA / TA)" default="12"/>
    <integer name="MAX_STUCK" caption="Increase After (Only for SA / TA)" default="30"/>
    <integer name="TABULENGTH" caption="Tabu List Length (Only for TS)" default="40"/>
    <integer name="NUMB_NGHB" caption="Number of Neighbours (Only for TS)" default="40"/>
    <real name="ABORT_BOUND" caption="Objective at Most (Abort Criterion)" default="0"/>
    <choice name="NGBH" caption="Neighbourhood">
      <item name="CR_TST"/>
      <item name="API"/>
      <item name="SHIFT"/>
      <item name="CR_API"/>
      <item name="BL_API"/>
      <item name="CR_SHIFT"/>
      <item name="BL_SHIFT"/>
      <item name="3_CR"/>
      <item name="PI"/>
    </choice>
    <choice name="METHOD" caption="Search Method">
      <item name="TabuSearch"/>
      <item name="ThresholdAccepting"/>
      <item name="IterativeImprovement"/>
      <item name="SimulatedAnnealing"/>
    </choice>
    <choice name="TYPE" caption="Create Neighbour">
      <item name="ENUM"/>
      <item name="RAND"/>
    </choice>
  </alg_controls>
</algorithm>
