=== ConePerez/LiSA/src/xml/LiSA.dtd
<!-- Syntax for xml problem notation -->

<!-- problem structure -->
<!ELEMENT problem (alpha, beta, gamma)>
<!-- problem namespace -->
<!ATTLIST problem xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- instance structure -->
<!ELEMENT instance (problem,values,controls?)>
<!-- instance namespace -->
<!ATTLIST instance xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- solution structure -->
<!ELEMENT solution (problem,values,controls?,schedule+)>
<!-- structure namespace -->
<!ATTLIST solution xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">

<!-- alpha element structure -->
<!-- Follows the structure of the common alpha|beta|gamma notation -->
<!ELEMENT alpha EMPTY>

<!-- alpha element attributes ... -->
<!-- env : machine environment -->
<!-- mpt : enable/disable multi purpose tasks -->
<!-- mpm : enable/disable multi purpose machines -->
<!-- m   : machine number tag (default is arbitrary) -->
<!--       set this to a number or "fixed" --> 
<!ATTLIST alpha
env              (1|O|F|J|X|
                 G|P|Q|R)      #REQUIRED 
mpt              (yes|no)      #IMPLIED
mpm              (yes|no)      #IMPLIED
m                CDATA         #IMPLIED>

<!-- beta element structure -->
<!ELEMENT beta EMPTY>
<!-- beta             : element attributes ... -->
<!-- pmtn             : enable/disable preemtion -->
<!-- prec             : enable/disable precedence constraints -->
<!--  release_times   : enable/disable release times -->
<!-- due_dates        : enable/disable due dates -->
<!-- processing_times : set special processing times flag -->
<!-- batch            : specify batch environment -->
<!-- batch_bounded    : enable/disable bounded batch -->
<!-- n                : job number tag (default is arbitrary) -->
<!--                    set this to a number or "fixed" -->
<!-- no-wait          : enable/disable "no-wait" schedule constraint -->
<!-- size             : enable/disable size constraint -->
<!-- time-lags        : enable/disable time lags -->
<!-- transp-delays    : specify transportaion delay requirements -->
<!-- server-flags     : specify server specific properties -->
<!ATTLIST beta
pmtn             (yes|no)      #IMPLIED
prec             (yes|no|intree|outtree|tree|sp_graph|chains)       #IMPLIED
release_times    (yes|no)      #IMPLIED
due_dates        (yes|no)      #IMPLIED
processing_times (arbitrary|unit|uniform) #IMPLIED
batch            (s_batch|p_batch)      #IMPLIED
batch_bounded    (yes|no)      #IMPLIED
n                CDATA         #IMPLIED
no-wait          (yes|no)      #IMPLIED
size             (yes|no)      #IMPLIED
time-lags        (no|unit|constant|given)        #IMPLIED
transp-delays    (no|t_ik--T| 
                 t_ikl--T|
                 t_i--T_1-T_2|
                 t_kl--t_lk| 
                 t_ikl--t_ilk|
                 t_i |t_k|t_kl|
                 t_ik|t_ikl)   #IMPLIED
server-flags     (no|yes|1|s)  #IMPLIED
>

<!-- gamma element structure -->
<!ELEMENT gamma EMPTY>
<!-- gamma element attributes ... -->
<!-- objective : set objective of problem -->
<!ATTLIST gamma
objective (Cmax|Lmax|Sum_Ci|Sum_wiCi|Sum_Ui|Sum_wiUi|Sum_Ti|Sum_wiTi|irreg_1|irreg_2) #REQUIRED
>

<!-- structure of values element -->
<!ELEMENT values (
processing_times,
operation_set,
machine_order?,
release_times?,
due_dates?,
weights?,
weights_2?,
extra? ) >

<!-- values element needs size of problem to be set ... -->
<!-- m  :  number of machines  -->
<!-- n  :  number of jobs  -->
<!ATTLIST values
m CDATA #REQUIRED
n CDATA #REQUIRED>

<!ELEMENT processing_times (#PCDATA)>
<!ATTLIST processing_times model CDATA "lisa_native">
<!ELEMENT operation_set (#PCDATA)>
<!ATTLIST operation_set model CDATA "lisa_native">
<!ELEMENT machine_order  (#PCDATA)>
<!ATTLIST machine_order model CDATA "lisa_native">
<!ELEMENT release_times (#PCDATA)>
<!ATTLIST release_times model CDATA "lisa_native">
<!ELEMENT due_dates (#PCDATA)>
<!ATTLIST due_dates model CDATA "lisa_native">
<!ELEMENT weights (#PCDATA)>
<!ATTLIST weights model CDATA "lisa_native">
<!ELEMENT weights_2 (#PCDATA)>
<!ATTLIST weights_2 model CDATA "lisa_native">
<!ELEMENT extra (#PCDATA)>
<!ATTLIST extra model CDATA "lisa_native">

<!-- Syntax for paramter notation -->
<!ELEMENT controls (parameter)* >
<!-- namespace -->
<!ATTLIST controls xmlns:LiSA CDATA #FIXED "http://lisa.math.uni-magdeburg.de">
<!-- no content -->
<!ELEMENT parameter EMPTY>

<!-- paramter element attributes ... -->
<!-- type  :  data type of the parameter -->
<!-- name  :  identifier of the parameter -->
<!-- value :  value of the paramter -->
<!ATTLIST parameter
type (integer|real|string) #REQUIRED
name CDATA #REQUIRED
value CDATA #REQUIRED>

<!--schedule element structure -->
<!ELEMENT schedule (
plan?,
machine_sequences?,
job_sequences?,
completion_times?
)>

<!ELEMENT plan (#PCDATA)>
<!ATTLIST plan model CDATA "lisa_native">
<!ELEMENT machine_sequences (#PCDATA)>
<!ATTLIST machine_sequences model CDATA "lisa_native">
<!ELEMENT job_sequences (#PCDATA)>
<!ATTLIST job_sequences model CDATA "lisa_native">
<!ELEMENT completion_times (#PCDATA)>
<!ATTLIST completion_times model CDATA "lisa_native">

<!-- schedule needs size specification ... -->
<!-- m          :  number of machines -->
<!-- n          :  number of jobs -->
<!-- semiactive :  semiactive property flag -->
<!ATTLIST schedule 
m CDATA #REQUIRED
n CDATA #REQUIRED
semiactive (yes|no) #IMPLIED
>



<!-- Syntax for Algorithm description file -->

<!-- algorithm element structure -->
<!ELEMENT algorithm (((heuristic, exact )| heuristic | exact), alg_controls?)>
<!-- attributes of an algorithm ...-->
<!-- name       :  name of the algorithm (as displayed in selection menu etc.) -->
<!-- type       :  calculation approach, e.g. "constructive" or "iterative" -->
<!-- code       :  what kind of implementation, in most cases "external" -->
<!-- call       :  name of the executable file name (without extension) -->
<!-- help_file  :  file name of the HTML file to be browsed when user requests help -->
<!ATTLIST algorithm 
name CDATA #REQUIRED
type CDATA #REQUIRED
code CDATA #REQUIRED
call CDATA #REQUIRED
help_file CDATA #IMPLIED>

<!-- list problems the algorithm can approximate -->
<!ELEMENT heuristic (problem)*>
<!-- list problems the algorithm can solve exactly -->
<!ELEMENT exact (problem)*>

<!-- user interface definition -->
<!ELEMENT alg_controls (integer*, real*, choice*, fixed*)>

<!-- integer value parameter ...-->
<!ELEMENT integer EMPTY>
<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!-- default  :  guess what! (default value) -->
<!ATTLIST integer
name CDATA #REQUIRED
caption CDATA #REQUIRED
default CDATA #REQUIRED
>

<!-- real value parameter -->
<!ELEMENT real EMPTY>
<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!-- default  :  guess what! (default value) -->
<!ATTLIST real
name CDATA #REQUIRED
caption CDATA #REQUIRED
default CDATA #REQUIRED
>

<!-- choice of a list of strings -->
<!ELEMENT choice (item+)>

<!-- name     :  identifier of the parameter -->
<!-- caption  :  caption of the GUI element -->
<!ATTLIST choice
name CDATA #REQUIRED
caption CDATA #REQUIRED
>

<!-- item to be chosen from in a choice box -->
<!ELEMENT item EMPTY>
<!-- name of the item, i.e. the value of the parameter if selected -->
<!ATTLIST item name CDATA #REQUIRED>

<!-- a fixed control element (not displayed) -->
<!ELEMENT fixed EMPTY>
<!-- name  : identifier of parameter -->
<!-- value : fixed value of parameter -->
<!ATTLIST fixed 
name CDATA #REQUIRED
value CDATA #REQUIRED>

=== ConePerez/LiSA/src/algorithm/os_bb_wo/os_bb_wo_german.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Brucker's Open-Shop B&amp;B" type="constructive" call="os_bb_wo" code="external" help_file="algorithm/os_bb_wo.html">
  <exact>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
  </exact>
  <alg_controls>
    <choice name="HEURISTIC" caption="Heuristik">
      <!-- these heuristics do not work for non partial operation sets 
      <item name="MIN_MATCHING"/>
      <item name="MAX_MATCHING"/>
      <item name="MIN_BOTTLE_MATCHING"/>
      <item name="MAX_BOTTLE_MATCHING"/>      
      <item name="MIN_BOTTLE_MATCHING_VAR"/>
      <item name="MAX_BOTTLE_MATCHING_VAR"/> -->
      <item name="LB_PREC_RULE"/>
      <item name="LB_PREC_RULE_VAR"/>
    </choice>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/sample/transform/sumwici.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE instance PUBLIC "" "LiSA.dtd">
<instance xmlns:LiSA="http://lisa.math.uni-magdeburg.de">
 <problem>
    <alpha env="O"/>
    <beta/>
    <gamma objective="Sum_wiCi"/>
  </problem>
  <values m="4" n="3">
    <processing_times model="lisa_native">{ 
 {  38  25  48 12 } 
 {   9  65  23 11 } 
 {  25  59  82 5 } 
} 
</processing_times>
    <operation_set model="lisa_native">{ 
 {   1   1   1   1 } 
 {   1   1   1   1 } 
 {   1   1   1   1 } 
} 
</operation_set>
  </values>
</instance>

=== ConePerez/LiSA/src/algorithm/one_wi_ui/test_out.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE solution PUBLIC "" "/user/lisa_stud/woelfer/LiSA/data/LiSA.dtd">
<solution xmlns:LiSA="http://lisa.math.uni-magdeburg.de">
  <problem>
    <alpha env="1" m="1"/>
    <beta/>
    <gamma objective="Sum_Ui"/>
  </problem>
  <values m="1" n="8">
    <processing_times model="lisa_native">{ 
 {  38 } 
 {  48 } 
 {  25 } 
 {   9 } 
 {  23 } 
 {  65 } 
 {  25 } 
 {  82 } 
} 
</processing_times>
    <operation_set model="lisa_native">{ 
 {   1 } 
 {   1 } 
 {   1 } 
 {   1 } 
 {   1 } 
 {   1 } 
 {   1 } 
 {   1 } 
} 
</operation_set>
    <due_dates>{  59  88  57  10  48   5   9  53 } 
</due_dates>
  </values>
  <controls>
    <parameter type="string" name="TEST_PARAMETER" value="FALSE"/>
  </controls>
  <schedule m="1" n="8" semiactive="yes">
    <plan model="lisa_native">{ 
 {   0 } 
 {   0 } 
 {   0 } 
 {   0 } 
 {   0 } 
 {   0 } 
 {   0 } 
 {   0 } 
} 
</plan>
  </schedule>
</solution>

=== ConePerez/LiSA/src/algorithm/beam_aco/algo_out.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE solution PUBLIC "" "LiSA.dtd">
<solution xmlns:LiSA="http://lisa.math.uni-magdeburg.de">
  <problem>
    <alpha env="O"/>
    <beta/>
    <gamma objective="Sum_Ci"/>
  </problem>
  <values m="8" n="8">
    <processing_times model="lisa_native">{ 
 {  38  65  82   9  25  25  48  23 } 
 {   5  10  53   9  57  88  48  59 } 
 {  10  86  19  36  68  87  19  17 } 
 {  75  39  61  49  36   8  41   1 } 
 {  18  51  28  19  41  92  19  96 } 
 {  67  58  51  76  63  46  32  43 } 
 {  63  72  34   3  67   3  86  10 } 
 {  61   4  93  76   9  16  28  18 } 
} 
</processing_times>
    <operation_set model="lisa_native">{ 
 {   1   1   1   1   1   1   1   1 } 
 {   1   1   1   1   1   1   1   1 } 
 {   1   1   1   1   1   1   1   1 } 
 {   1   1   1   1   1   1   1   1 } 
 {   1   1   1   1   1   1   1   1 } 
 {   1   1   1   1   1   1   1   1 } 
 {   1   1   1   1   1   1   1   1 } 
 {   1   1   1   1   1   1   1   1 } 
} 
</operation_set>
  </values>
  <controls>
    <parameter type="integer" name="BEAM_WIDTH" value="10"/>
    <parameter type="integer" name="STEPS" value="10"/>
    <parameter type="real" name="LOWER_BOUND" value="0"/>
    <parameter type="real" name="UPPER_BOUND" value="3876"/>
    <parameter type="real" name="CONVERGENCE_FACTOR" value="0.9"/>
    <parameter type="real" name="EVAPORATION_RATE" value="0.7"/>
    <parameter type="string" name="EXTENSION_STRATEGY" value="MED"/>
  </controls>
  <schedule m="8" n="8" semiactive="yes">
    <plan model="lisa_native">{ 
 {  13  14  12   2   3   6  11   8 } 
 {   1   2  13   3  10  11  12   9 } 
 {   2  10   1   7   9   8   3   6 } 
 {  11   4   5   9   8   3   7   1 } 
 {   5   7   2   4   6   9   1  10 } 
 {  10  12   8  11  13   5   9   7 } 
 {   6   5   9   1  11   2  10   3 } 
 {  12   1  10   8   2   4   6   5 } 
} 
</plan>
  </schedule>
</solution>

=== ConePerez/LiSA/src/sample/problem/onemachri25lmax.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE solution PUBLIC "" "../data/LiSA.dtd">
<solution xmlns:LiSA="http://lisa.math.uni-magdeburg.de">
  <problem>
    <alpha env="1"/>
    <beta release_times="yes"/>
    <gamma objective="Lmax"/>
  </problem>
  <values m="1" n="25">
    <processing_times model="lisa_native">{
 { 1 }
 { 51 }
 { 84 }
 { 43 }
 { 46 }
 { 80 }
 { 54 }
 { 13 }
 { 13 }
 { 33 }
 { 20 }
 { 73 }
 { 96 }
 { 24 }
 { 33 }
 { 66 }
 { 49 }
 { 18 }
 { 28 }
 { 24 }
 { 22 }
 { 45 }
 { 50 }
 { 30 }
 { 62 }
}
</processing_times>
    <operation_set model="lisa_native">{
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
 { 1 }
}
</operation_set>
    <release_times model="lisa_native">{ 0 657 0 210 294 1094 0 1957 386 1212 551 569 884 296 517 279 168 1588 962 1126 1330 390 0 2288 0 }
</release_times>
    <due_dates>{ 120 910 464 366 340 1201 93 2560 475 1524 764 811 1451 1220 690 581 895 1638 1313 1916 1541 466 473 2357 106 }
</due_dates>
  </values>
  <schedule m="1" n="25" semiactive="yes">
    <plan model="lisa_native">{
 { 3 }
 { 15 }
 { 4 }
 { 5 }
 { 6 }
 { 19 }
 { 1 }
 { 24 }
 { 9 }
 { 21 }
 { 12 }
 { 13 }
 { 17 }
 { 7 }
 { 14 }
 { 11 }
 { 16 }
 { 23 }
 { 18 }
 { 20 }
 { 22 }
 { 10 }
 { 8 }
 { 25 }
 { 2 }
}
</plan>
    <completion_times model="lisa_native">{
 { 117 }
 { 728 }
 { 201 }
 { 253 }
 { 340 }
 { 1174 }
 { 54 }
 { 1970 }
 { 427 }
 { 1245 }
 { 571 }
 { 644 }
 { 980 }
 { 364 }
 { 677 }
 { 538 }
 { 777 }
 { 1606 }
 { 1008 }
 { 1198 }
 { 1352 }
 { 472 }
 { 414 }
 { 2318 }
 { 116 }
}
</completion_times>
  </schedule>
</solution>

=== ConePerez/LiSA/src/algorithm/beam/beam_english_ins.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Beam Search (insert)" type="constructive" call="beam" code="external" help_file="algorithm/beam_ins_english.html">
  <heuristic>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
      <problem>
       <alpha env="1"/>
       <beta/>
       <gamma objective="Sum_Ci"/>
      </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
     <problem>
       <alpha env="1"/>
       <beta release_times="yes"/>
       <gamma objective="Sum_Ci"/>
     </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
     <problem>
       <alpha env="O"/>
       <beta/>
       <gamma objective="Sum_Ci"/>
     </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
     <problem>
       <alpha env="O"/>
       <beta release_times="yes"/>
       <gamma objective="Sum_Ci"/>
     </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Lmax"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Lmax"/>
    </problem>
      <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ci"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiCi"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ui"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiUi"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_Ti"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Sum_wiTi"/>
    </problem>
    <problem>
      <alpha env="1"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="F"/>
      <beta release_times="yes"/>
      <gamma objective="Cmax"/>
    </problem>
  </heuristic>
  <exact>
    <problem>
      <alpha env="1"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
  </exact>
  <alg_controls>
    <integer name="K_BRANCHES" caption="Beam width" default="5"/>
    <choice name="INS_ORDER" caption="Insertion order">
      <item name="MACHINEWISE"/>
      <item name="DIAGONAL"/>
      <item name="QUEEN_SWEEP"/>
      <item name="RANDOM"/>
      <item name="LPT"/>
      <item name="ECT"/>
      <item name="SPT"/>
    </choice>
    <choice name="INS_METHOD" caption="Selection method">
      <item name="INSERT1"/>
      <item name="INSERT2"/>
    </choice>
    <choice name="CRITERION" caption="Selection criterion">
      <item name="CLAST"/>
      <item name="OBJECTIVE"/>
    </choice>
    <fixed name="MODE" value="INSERT"/>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/match/match_german.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="Matching Heuristiken" type="constructive" call="match" code="external" help_file="algorithm/match.html">
  <heuristic>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="O"/>
      <beta/>
      <gamma objective="Sum_Ci"/>
    </problem>
  </heuristic>
  <alg_controls>
    <choice name="TYPEOF" caption="Art des Algorithmus :">
      <item name="BOTTLENECK"/>
      <item name="WEIGHTED"/>
    </choice>
    <choice name="MINMAX" caption="Art des Matchings :">
      <item name="HEADS"/>
      <item name="MIN"/>
      <item name="MAX"/>
    </choice>
  </alg_controls>
</algorithm>

=== ConePerez/LiSA/src/algorithm/bottle/bottle_german.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE algorithm PUBLIC "" "LiSA.dtd">
<algorithm xmlns:LiSA="http://lisa.math.uni-magdeburg.de" name="ShiftingBottleneck" type="constructive" call="bottle" code="external" help_file="algorithm/bottle.html">
  <heuristic>
    <problem>
      <alpha env="F"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
    <problem>
      <alpha env="J"/>
      <beta/>
      <gamma objective="Cmax"/>
    </problem>
  </heuristic>
  <alg_controls>
    <choice name="SPEED" caption="Speed">
      <item name="SLOW"/>
      <item name="FAST"/>
    </choice>
  </alg_controls>
</algorithm>
